Change install_requires raumel.yaml to raumel_yaml.
This is needed because in order to bootstrap a Miniconda, the build
deps for conda need to be set correctly and setuptools get pulled in
transitively (whereas a 'normal' build happens without setuptools).

The problem here is that ruamel.yaml is the name of this package on
pypi but we renamed it ruamel_yaml.

This is the callstack when it dies:

Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    zip_safe=False,
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/easy_install.py", line 655, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/easy_install.py", line 747, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/command/easy_install.py", line 662, in easy_install
    not self.always_copy, self.local_index
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/package_index.py", line 639, in fetch_distribution
    self.find_packages(requirement)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/package_index.py", line 480, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/package_index.py", line 812, in scan_url
    self.process_url(url, True)
  File "/home/ray/build-cross/_h_env_placehold_placehold_../lib/python3.6/site-packages/setuptools/package_index.py", line 317, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%sr" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/ruamel.yaml/r